#! /bin/bash

# dhclient-script for Linux. Dan Halbert, March, 1997.
# Updated for Linux 2.[12] by Brian J. Murrell, January 1999.
# Modified for Debian.  Matt Zimmerman and Eloy Paris, December 2003
# Modified to remove useless tests for antiquated kernel versions that
# this doesn't even work with anyway, and introduces a dependency on /usr
# being mounted, which causes cosmetic errors on hosts that NFS mount /usr
# Andrew Pollock, February 2005
# Modified to work on point-to-point links. Andrew Pollock, June 2005
# Modified to support passing the parameters called with to the hooks. Andrew Pollock, November 2005

# The alias handling in here probably still sucks. -mdz

make_resolv_conf() {

	if [ "$new_domain_name" -o "$new_domain_name_servers" ]; then

		local new_resolv_conf=/tmp/resolv.conf.dhclient-new
		
		rm -f $new_resolv_conf
	
		if [ "$new_domain_name" ]; then
			echo domain ${new_domain_name%% *} >>$new_resolv_conf
		fi
		
		if [ "$new_domain_search" ]; then
		
			#new_domain_search="${new_domain_search% }"
			
			if [ "$new_domain_name" ]; then

				domain_in_search_list=""
	
				for domain in "$new_domain_search"; do
					if [ "$domain" = "$new_domain_name" ]; then
						domain_in_search="Yes"
					fi
				done
				
				if [ ! "$domain_in_search" ]; then
					new_domain_search="$new_domain_name $new_domain_search"
				fi
			fi
		
			echo "search ${new_domain_search}" >> $new_resolv_conf
			
		elif [ "$new_domain_name" ]; then

			echo "search ${new_domain_name}" >> $new_resolv_conf
		
		fi
	
		if [ "$new_domain_name_servers" ]; then
		
			for nameserver in $new_domain_name_servers; do
				echo nameserver $nameserver >>$new_resolv_conf
			done
		
		else # keep 'old' nameservers
			sed -n /^\w*[Nn][Aa][Mm][Ee][Ss][Ee][Rr][Vv][Ee][Rr]/p /etc/resolv.conf >>$new_resolv_conf
		fi
        
		cmp -s $new_resolv_conf /etc/resolv.conf
        
		local RC=$?
        
		if [ "$RC" -eq "1" ]
		then
			chown --reference=/etc/resolv.conf $new_resolv_conf
			chmod --reference=/etc/resolv.conf $new_resolv_conf
			cp -fv $new_resolv_conf /etc/resolv.conf
		fi
	fi
}

